# Site settings
title: Alessandro Scisca
description: About
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shishka0.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alessandro Scisca
user_description: Fueled by passion
user_title: MSc. Digital Systems Engineering
email: alessandro.scisca1@gmail.com
# twitter_username: lorem_ipsum
github_username: shishka0
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
